# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('av_returns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('size', models.BigIntegerField(default=0)),
                ('s3_key', models.TextField()),
                ('s3_bucket', models.TextField()),
                ('s3_region', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL)),
                ('tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='av_returns.Return')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
