# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 12:00
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('medical_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('real_estate_taxes', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('mortgage_interest', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('tax_preparation_fees', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('union_dues', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('subscriptions', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('professional_dues', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('telephone', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('investment_management_fees', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('job_hunting_costs', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('travel', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('entertainment', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('supplies', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('transportation', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('charitable_contributions', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='middle name')),
                ('dob', models.DateField(blank=True, null=True)),
                ('ssn', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(code='bad_ssn', message='SSN should be 9 digits.', regex='^\\d{9}$')])),
                ('relationship', models.CharField(choices=[('DAUGHTER', 'Daughter'), ('SON', 'Son'), ('AUNT', 'Aunt'), ('BROTHER', 'Brother'), ('FOSTER_CHILD', 'Foster Child'), ('GRANDCHILD', 'Grandchild'), ('GRANDPARENT', 'Grandparent'), ('HALF_BROTHER', 'Half Brother'), ('HALF_SISTER', 'Half Sister'), ('NEPHEW', 'Nephew'), ('NIECE', 'Niece'), ('NONE', 'None'), ('OTHER', 'Other'), ('PARENT', 'Parent'), ('SISTER', 'Sister'), ('STEPBROTHER', 'Stepbrother'), ('STEPCHILD', 'Stepchild'), ('STEPSISTER', 'Stepsister'), ('UNCLE', 'Uncle')], max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('type', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('year', models.SmallIntegerField()),
                ('is_dependent', models.NullBooleanField()),
                ('county', models.TextField(blank=True)),
                ('filing_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED_JOINT', 'Married, filing jointly'), ('MARRIED_SEPARATE', 'Married, filing separately'), ('HEAD', 'Head of household'), ('WIDOW', 'Widow')], max_length=32, null=True)),
                ('return_status', models.CharField(choices=[('DRAFT', 'Information Submitted'), ('REVIEW', 'Under CPA Review'), ('COMPLETE', 'Completed'), ('READY', 'Ready to file'), ('FILED', 'Filed')], default='DRAFT', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='middle name')),
                ('dob', models.DateField(blank=True, null=True)),
                ('ssn', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(code='bad_ssn', message='SSN should be 9 digits.', regex='^\\d{9}$')])),
                ('tax_return', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='av_returns.Return')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='av_returns.Return'),
        ),
        migrations.AddField(
            model_name='dependent',
            name='tax_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='av_returns.Return'),
        ),
        migrations.AddField(
            model_name='commonexpenses',
            name='tax_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='av_returns.Return'),
        ),
        migrations.AlterUniqueTogether(
            name='return',
            unique_together=set([('user', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together=set([('tax_return', 'type')]),
        ),
    ]
