# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='county',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
