# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('av_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='firm name, as you would like your clients to see it')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
