# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('av_account', '0002_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='avuser',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='av_account.Firm'),
        ),
    ]
