# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_account', '0005_auto_20180527_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='avuser',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
