# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_account', '0006_avuser_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avuser',
            name='trial_end',
            field=models.DateTimeField(null=True),
        ),
    ]
