# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-29 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('av_account', '0008_communications_trial_end_reminders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avuser',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='avuser',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='avuser',
            name='trial_end',
        ),
        migrations.AddField(
            model_name='firm',
            name='boss',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boss_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firm',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firm',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='firm',
            name='trial_end',
            field=models.DateTimeField(null=True),
        ),
    ]
