# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-29 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_account', '0009_auto_20180629_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='stripe_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
