# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-30 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_account', '0010_auto_20180629_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='communications',
            name='agreed_terms',
            field=models.DateTimeField(null=True, verbose_name='date agreed to terms'),
        ),
    ]
