# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-20 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_account', '0011_communications_agreed_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='communications',
            name='trial_change_notice',
            field=models.IntegerField(default=0),
        ),
    ]
