# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('subject', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
